function calcMinRanges(trackedDir,resultsDir)

% Function to calculate minimum ranges for joint positions, 
%
% If we want to allow initial and final torque controls to be different,
% then we need to use a linear polynomial when fitting torque control
% data.
%
% Author: B.J. Fregly 10/16/2025

close all

if nargin < 2
    trialName = 'Trial12_Gait';
	resultsFolder = 'toResults';
	nHarmonics = 14;
end

% Define inputs
degree = 1;

% Read in torque control data generated by a torque-driven TO run
infile = sprintf('%s_torqueControls.sto',trialName);
dataStruct = importdata(infile);
time = dataStruct.data(:,1);
torqueData = dataStruct.data(:,2:end);
headerlines = dataStruct.textdata;
colHeaders = dataStruct.colheaders;

% Perform polyFourier fit of torque control data for one coordinate at a time
tSpan = max(time)-min(time);
w = 2.0*pi/tSpan;
[nFrames,nControls] = size(torqueData);
ti = time(1,1);
tf = time(end,1);
dt = time(2,1)-time(1,1);
timeID = [ti:dt:tf]';
nFramesID = size(timeID,1);
torqueDataSmoothed = zeros(nFrames,nControls);
torqueDataSmoothedID = zeros(nFramesID,nControls);

for i = 1:nControls
    % Calculate polyFourier coefficients for torque control data
    % Replace the spurious last time point with the first time point to
    % improve the fitting process
    y = [torqueData(1:end-1,i); torqueData(1,i)];
    coefs = polyFourierCoefs(time,y,degree,nHarmonics);
	
    % Form the fitted torque control curves
    % Include the last time point in the fit
    derivs = 0;
    fit = polyFourierCurves(coefs,w,time,degree,derivs);
    yFit = fit(:,1);
    fitID = polyFourierCurves(coefs,w,timeID,degree,derivs);
    yFitID = fitID(:,1);
	
    % Save smoothed fitted data
    torqueDataSmoothed(:,i) = yFit;
    torqueDataSmoothedID(:,i) = yFitID;
	
    % Calculate RMS error
    % Omit the spurious last time point from the error calculation
    errors = yFit-y;
    rmsError = sqrt(errors'*errors/nFrames);
    maxError = max(abs(errors));
	
    % Plot the original and fitted curves as a check
    plot(time,y,'k-',time,yFit,'r-')
    xlabel('time')
    ylabel(sprintf('torque %d',i))
    title(sprintf('RMS error = %4.2f Nm, max error = %4.2f Nm',rmsError,maxError))
    
    % pause
end

close all

% Output new torque control files with polyFourier smoothed controls
outfile = sprintf('%s_controlTorques_smoothed.sto',trialName);
outfileID = sprintf('%s_id_smoothed.sto',trialName);

fprintf('Outputting smoothed torque control data file . . .\n')
fid = fopen(outfile,'w');
fidID = fopen(outfileID,'w');
nCols = size(headerlines,2);
for i = 1:4
    fprintf(fid,'%s\n',headerlines{i,1});
    fprintf(fidID,'%s\n',headerlines{i,1});
end
for j = 1:nCols-1
    fprintf(fid,'%s\t',headerlines{5,j});
    fprintf(fidID,'%s\t',headerlines{5,j});
end
fprintf(fid,'%s\n',headerlines{5,nCols});
fprintf(fidID,'%s\n',headerlines{5,nCols});
nRows = size(time,1);
nCols = nControls;
for i = 1:nRows
    fprintf(fid,'%22.17f\t',time(i,1));
    for j = 1:nCols-1
        fprintf(fid,'%22.17f\t',torqueDataSmoothed(i,j));
    end
    fprintf(fid,'%22.17f\n',torqueDataSmoothed(i,nCols));
end
nRows = size(timeID,1);
for i = 1:nRows
    fprintf(fidID,'%22.17f\t',timeID(i,1));
    for j = 1:nCols-1
        fprintf(fidID,'%22.17f\t',torqueDataSmoothedID(i,j));
    end
    fprintf(fidID,'%22.17f\n',torqueDataSmoothedID(i,nCols));
end
fclose(fid);
fclose(fidID);
end