function filterTorqueControls(trialName,resultsFolder,nHarmonics)

% Function to polyFourier fit of one cycle of gait torque control data
% using polyFourier fitting.
%
% If we want to allow initial and final torque controls to be different,
% then we need to use a linear polynomial when fitting torque control
% data.
%
% Author: B.J. Fregly 10/19/2025

close all

if nargin < 3
    trialName = 'Trial12_Gait';
	resultsFolder = 'toResultsFiltered';
	nHarmonics = 21;
end

% Define inputs
degree = 1;

% Read in torque control data generated by a torque-driven TO run
infile = sprintf('%s\\%s_torqueControls.sto',resultsFolder,trialName);
dataStruct = importdata(infile);
time = dataStruct.data(:,1);
torqueData = dataStruct.data(:,2:end);
headerlines = dataStruct.textdata;

% Perform polyFourier fit of torque control data for one coordinate at a time
tSpan = max(time)-min(time);
w = 2.0*pi/tSpan;
[nFrames,nControls] = size(torqueData);
ti = time(1,1);
tf = time(end,1)
freq = 1/tf;
dt = time(2,1)-time(1,1);
torqueDataFiltered = zeros(nFrames,nControls);

for i = 1:nControls
    % Calculate polyFourier coefficients for torque control data
    y = torqueData(:,i);
    coefs = polyFourierCoefs(time,y,freq,degree,nHarmonics);
	
    % Form the fitted torque control curves
    % Include the last time point in the fit
    derivs = 0;
    fit = polyFourierCurves(coefs,freq,time,degree,derivs);
    yFit = fit(:,1);
	
    % Save filtered fitted data
    torqueDataFiltered(:,i) = yFit;
	
    % Calculate RMS error
    % Omit the spurious last time point from the error calculation
    errors = yFit-y;
    rmsError = sqrt(errors'*errors/nFrames);
    maxError = max(abs(errors));
	
    % Plot the original and fitted curves as a check
    plot(time,y,'k-',time,yFit,'r-')
    xlabel('time')
    ylabel(sprintf('torque %d',i))
    title(sprintf('RMS error = %4.2f Nm, max error = %4.2f Nm',rmsError,maxError))
    
    pause
end

close all

% Output new torque control files with polyFourier smoothed controls
outfile = sprintf('%s\\%s_torqueControls_filtered.sto',resultsFolder,trialName);

fprintf('Outputting filtered torque control data file . . .\n')
fid = fopen(outfile,'w');
nCols = size(headerlines,2);

for i = 1:4
    fprintf(fid,'%s\n',headerlines{i,1});
end

for j = 1:nCols-1
    fprintf(fid,'%s\t',headerlines{5,j});
end

fprintf(fid,'%s\n',headerlines{5,nCols});
nRows = size(time,1);
nCols = nControls;

for i = 1:nRows
    fprintf(fid,'%22.17f\t',time(i,1));
    for j = 1:nCols-1
        fprintf(fid,'%22.17f\t',torqueDataFiltered(i,j));
    end
    fprintf(fid,'%22.17f\n',torqueDataFiltered(i,nCols));
end

fclose(fid);

end